language: php
php:
- '5.5'

script: echo "We don't have tests yet :("

before_deploy:
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  file: "plugin-prestashop-onepay-$TRAVIS_TAG.zip"
  skip_cleanup: true
  api_key:
    secure: eB59XsEt2kTtt9eTy9t7GwctnACeNmz8s7WBZZnMZFNqLTOueX59hOERrAlw41xXX0zotKrKzgygCqblnzzEoQbF+Mlf7wfxhcR8wtrY2rNWsYtNlck5FrATC6bj+XSNN10SV/61DoGaT9nrnU2zCXtBeljUdtT9owKDF87jlNKY5E4LaFSPcYimdsiuO8UL9qGea73QPqwoK+uGvnUpxyK6jb8qmXCm1a/2BMq0zcSZ7lD53L9snz9vXbki1+WC6/j3XM8IuFqWM7ZbRjcqQ9+D2vXjboHy7TVjpNNjqzs8Ow2/vcyqVm9KEQQR2//ZwF6D4FZS5lwJNaVfUYzbdAu/vgdF8rzh4Uqmnte20sq4PhvOmQi4lgiYiqly21SzTS1wQR5TNwB26x2IUVli77uSdqOD4hdAt8UgosDt7TaY0CpFSExh6g+uD0judABYS9cWeia43M6R5lHf0xpprR6pRibhe4wOSvmhDy3X563r5VhC3VlDbQrwGY8kCSALl3YWyB3iziNqlG3h3isapMRldXLJEhaIUPPUOFUzRGvMpys8HNMCtAjdae/3YDkphfkWE8jCA5VfKPgpPqx/nojTFsNBJvkCbU3kT4C+mHDP5q/CV1+1/+954P4FaYZBSdUy/xs78Px0/O34OP6AMqmwG0sYVu4EG6z5RSEwcWw=
  on:
    repo: TransbankDevelopers/transbank-plugin-prestashop-onepay
    tags: true
